version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@1

jobs:
  trigger-dynamic:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Import and Trigger Dynamic Config
          command: echo "Using dynamic.yml for workflow"

workflows:
  version: 2
  setup:
    jobs:
      - continuation/continue:
          configuration_path: .circleci/dynamic.yml