version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@1

jobs:
  trigger-dynamic:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Import and Trigger Dynamic Config
          command: echo "Using dynamic.yml for workflow"

  generate-ci:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install jinja2 pyyaml
      - run:
          name: Execute Python Script
          command: python .circleci/generate_ci.py
      - run:
          name: ls dir
          command: ls -alh

      - run:
          name: ls dir
          command: ls -alh .circleci/ && sleep 10

      - persist_to_workspace:
          root: workspace
          paths:
            - dynamic.yml

workflows:
  version: 2
  setup:
    jobs:
      - generate-ci
      - continuation/continue:
          configuration_path: dynamic.yml
          requires:
            - generate-ci