version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Hello World
          command: echo "hello world" && sleep 10

  say-hello-2:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Hello World
          command: echo "hello world 2" && sleep 10

workflows:
  version: 2
  dynamic-workflow:
    jobs:
      - say-hello
      - say-hello-2